### PR TITLE
Add dependencies required to run jdaviz on RSP

### PR DESCRIPTION
**Pull request by haticekaratay**
This PR updates the dependencies required for JDavis to run smoothly on our platform. The dependencies have been directly aligned with those listed in JDaviz's pyproject.toml file. You can review the reference file here: https://github.com/spacetelescope/jdaviz/blob/main/pyproject.toml
**Background:**
During the testing of these updated dependencies, I encountered compatibility issues between our platform's current opencv version and numpy 2.0 or higher. Given the challenges in removing or updating the opencv-python package from our platform—and unsure how to proceed with such a task—I opted for a workaround by adjusting our numpy version to avoid conflicts. I know @cmurray-astro is also looking into this issue.

### CODE REVIEW

**Comment by cganley1** [comment]
@haticekaratay With these changes, numpy was downgraded to 1.* to accommodate jdaviz. Can you run these notebooks again and let me know if they are behaving as expected?

**Comment by haticekaratay** [comment]
> @haticekaratay With these changes: #34, numpy was downgraded to 1.* to accommodate jdaviz. Can you run these notebooks again and let me know if they are behaving as expected?

Hi, @cganley1, thank you! I successfully installed Jdaviz on the platform, and there are no longer installation issues related to numpy2 from the base image.  However, we're still encountering the problem of images not being displayed on the viewer. We also know that Jdaviz runs smoothly on the Jwebbinar platform. Is it possible to maybe replicate it on the RSP? Thanks

**Comment by jaytmiller** [comment]
Hi Hatice,  if you have a notebook and corresponding data which illustrate what's not working that'd be a big help with our debug.   Can you pass those on?  (make sure it's OK for those to be public before posting them here.  otherwise we can Slack and/or upload them to Jira.)

**Comment by haticekaratay** [comment]
> Hi Hatice, if you have a notebook and corresponding data which illustrate what's not working that'd be a big help with our debug. Can you pass those on? (make sure it's OK for those to be public before posting them here. otherwise we can Slack and/or upload them to Jira.)

Hi @jaytmiller! The notebook I initially used to test the basic functionality of jdaviz can be found at this link: https://github.com/spacetelescope/jdaviz/blob/main/notebooks/concepts/imviz_simple_aper_phot.ipynb. Additionally, we have special notebooks being prepared by @bmorris3 to test L2 and L3 files. As of now, the image viewer is not displaying images on the platform and appears like this: 
image
Where it should have looked like this instead: 

image

**Comment by jaytmiller** [comment]
Great Hatice,  that looks like exactly what we need to debug,  thank you!

**Comment by cganley1** [comment]
@haticekaratay 

A new jdaviz kernel was created addressing these issues. See: https://github.com/spacetelescope/science-platform-images/pull/39

Please use the updated RSP and test your notebooks. You may need to alter your workflow, relying on the roman-cal kernel for data processing and the jdaviz kernel for visualization. Let me know if there are any issues.

**Comment by bmorris3** [comment]
Hi @cganley1 – that may be ok for testing for now, but pipeline users will need to visualize pipeline products throughout the reduction process, and that would be made much less convenient if they need separate kernels. Is that intended to be a temporary workaround?

**Comment by haticekaratay** [comment]
> @haticekaratay
> 
> A new jdaviz kernel was created addressing these issues. See: #39
> 
> Please use the updated RSP and test your notebooks. You may need to alter your workflow, relying on the roman-cal kernel for data processing and the jdaviz kernel for visualization. Let me know if there are any issues.

@cganley1, thank you for the update. I have built and tested the images using the notebook I shared in the thread. It performed well during my initial testing. However, Bret will develop a separate notebook specifically for conducting performance testing on the L2 and L3 files. We will keep you updated on our progress.

**Comment by cganley1** [comment]
We now have a working roman-cal phase 1 testing version that can support the roman-cal notebooks. This includes jdaviz in the base roman-cal kernel and includes the remaining requirements. The imviz notebook above was tested with the configuration and appeared working as intended.

The current versions of the requirements for roman-cal are frozen and maintained this way for stability. Therefore, I am closing the ticket.

If there are any issues regarding performance or requirements for the currently supported version, please submit a ticket to the team for review.

**Pull request closed without merging**
