### PR TITLE
updated packages, removed extraneous notebooks

### PR DESCRIPTION
**Pull request by cganley1**

### CODE REVIEW

**Comment by cganley1** [comment]
I am not sure why the jwebbinar check is failing. I was able to build successfully locally.

**Comment by jaytmiller** [comment]
If you still have your local image it'd be good to set FREEZE_CHILL=1,  re-source setup-env,  and type image-freeze.   Then assuming there are requirements in deployments/jwebbinar/env-frozen you should add and commit those then push it up  as part of this PR.   Other than that,  the build failure is a temporary mystery,  roman and tike installed exactly the same package in theory...    So update the frozen requirements and approved,  thanks for taking care of this!

**Comment by jaytmiller** [comment]
I made a comment earlier about saving frozen requirements,   then made the mistake of closing the PR.   It's a good idea to save frozen requirements if you can get them easily,  otherwise don't sweat it.

**Review by jaytmiller — APPROVED** [review]
It's a good idea to save frozen requirements if you can get them easily, otherwise don't sweat it.   (See my other comments for how).

**Comment by cganley1** [comment]
I had some issues with docker and capturing the frozen requirements. Those are now resolved and included the changes. Thanks @jaytmiller

**Review by jaytmiller — APPROVED** [review]
Looks great,  thanks!

**Pull request merged**
